apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "ebs-dynamic" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: Pod
apiVersion: v1
metadata: 
  name: nginx
  labels:
    name: expense
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: myvolume
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: ebs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    name: expense
    environment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80        